In [1]:
from PIL import Image
from keras.applications.vgg16 import preprocess_input
import base64
from io import BytesIO
import json
import random
import cv2
from keras.models import load_model
import numpy as np

from keras.preprocessing import image
model = load_model('facefeatures_new_model_final.h5')

In [2]:
# Loading the cascades
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')


In [3]:
def face_extractor(img):
    # Function detects faces and returns the cropped face
    # If no face detected, it returns the input image
    
    #gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(img, 1.3, 5)
    
    if faces is ():
        return None
    
    # Crop all faces found
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        cropped_face = img[y:y+h, x:x+w]

    return cropped_face


In [6]:
# Doing some Face Recognition with the webcam
video_capture = cv2.VideoCapture(0)
while True:
    _, frame = video_capture.read()
    #canvas = detect(gray, frame)
    #image, face =face_detector(frame)
    
    face=face_extractor(frame)
    if type(face) is np.ndarray:
        face = cv2.resize(face, (224, 224))
        im = Image.fromarray(face, 'RGB')
           #Resizing into 128x128 because we trained the model with this image size.
        img_array = np.array(im)
                    #Our keras model used a 4D tensor, (images x height x width x channel)
                    #So changing dimension 128x128x3 into 1x128x128x3 
        img_array = np.expand_dims(img_array, axis=0)
        pred = model.predict(img_array)
        print(pred)
                     
        name="None matching"
        
        if(pred[0][1]>0.5):
            name='Vraj'
        cv2.putText(frame,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    else:
        cv2.putText(frame,"No face found", (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    cv2.imshow('Video', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()

       

[[1. 0.]]
[[1.000000e+00 9.324045e-24]]
[[1.00000e+00 2.21178e-09]]
[[1.0000000e+00 1.6217788e-24]]
[[1.0000000e+00 1.0285046e-09]]
[[1.0000000e+00 2.3378613e-28]]
[[1.0000000e+00 6.5366285e-24]]
[[1.6417887e-12 1.0000000e+00]]
[[1.9049436e-20 1.0000000e+00]]
[[2.6354892e-18 1.0000000e+00]]
[[1.341696e-29 1.000000e+00]]
[[9.9999356e-01 6.4750675e-06]]
[[0.93033034 0.06966968]]
[[6.5120312e-06 9.9999344e-01]]
[[0.07501802 0.924982  ]]
[[1.0000000e+00 1.9849843e-24]]
[[9.999608e-01 3.919769e-05]]
[[1.0000000e+00 1.6701564e-10]]
[[9.999808e-01 1.916403e-05]]
[[3.6119715e-08 1.0000000e+00]]
[[1.1907702e-08 1.0000000e+00]]
[[9.9999905e-01 9.4537415e-07]]
[[1.0000000e+00 3.1855623e-18]]
[[1.0049447e-07 9.9999988e-01]]
[[9.9972504e-01 2.7491900e-04]]
[[9.9922967e-01 7.7030493e-04]]
[[0.13666737 0.8633326 ]]
[[9.9981397e-01 1.8608075e-04]]
[[0.99897575 0.0010243 ]]
[[7.8720223e-06 9.9999213e-01]]
[[8.2299509e-04 9.9917704e-01]]
[[1.000000e+00 9.543757e-09]]
[[9.9968612e-01 3.1395632e-04]]
[[0.